/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef CB2PSI2SPDF
#define CB2PSI2SPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class CB2PSI2SPdf : public RooAbsPdf {
public:
  CB2PSI2SPdf() {} ;
  CB2PSI2SPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _D,
        RooAbsReal& _E,
        RooAbsReal& _F);
  CB2PSI2SPdf(const CB2PSI2SPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CB2PSI2SPdf(*this,newname); }
  inline virtual ~CB2PSI2SPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;
  RooRealProxy E ;
  RooRealProxy F ;

  Double_t evaluate() const ;

private:

  ClassDef(CB2PSI2SPdf,1) // Your description goes here...
};

#endif
